name = "HighlyAbundant"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["HighlyAbundant"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false
relaxedAutoImplicit = false
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "6f604786851f312da512a988fd54eee4ca35dcf9"

[[lean_lib]]
name = "HighlyAbundant"
