name = "HighlyAbundant"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["HighlyAbundant"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false
relaxedAutoImplicit = false
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "79d0395a1825a6264ad5d269e35e60537518955e"

[[lean_lib]]
name = "HighlyAbundant"
