name = "HighlyAbundant"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["HighlyAbundant"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false
relaxedAutoImplicit = false
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "95fdbd69e13b7e6b08d6b2ea72cbb6dd26d0d5f8"

[[lean_lib]]
name = "HighlyAbundant"
